# Generated by Django 3.1.7 on 2021-03-13 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summoner_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='matchhistory',
            old_name='matchhistory_text',
            new_name='matchhistory',
        ),
        migrations.AlterField(
            model_name='matchhistory',
            name='summoner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.summoner'),
        ),
        migrations.DeleteModel(
            name='SummonerName',
        ),
    ]
