# Generated by Django 3.1.7 on 2021-03-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20210319_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='profile_icon_id',
            field=models.CharField(default=0, max_length=78),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summoner',
            name='summoner_level',
            field=models.CharField(default=0, max_length=78),
            preserve_default=False,
        ),
    ]
