# Generated by Django 3.1.7 on 2021-05-11 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20210319_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('queue', models.IntegerField()),
                ('match_duration', models.IntegerField()),
                ('date_played', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchList',
            fields=[
                ('match_list_id', models.IntegerField(primary_key=True, serialize=False)),
                ('champion', models.IntegerField()),
                ('role', models.CharField(max_length=6)),
                ('match_outcome', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('participant_index', models.IntegerField()),
                ('name', models.CharField(max_length=16)),
                ('pick', models.IntegerField()),
                ('ban', models.IntegerField()),
                ('summoner_spell_one', models.IntegerField()),
                ('summoner_spell_two', models.IntegerField()),
                ('item_one', models.IntegerField()),
                ('item_two', models.IntegerField()),
                ('item_three', models.IntegerField()),
                ('item_four', models.IntegerField()),
                ('item_five', models.IntegerField()),
                ('item_six', models.IntegerField()),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('champion_level', models.IntegerField()),
                ('primary_rune_one', models.IntegerField()),
                ('primary_rune_two', models.IntegerField()),
                ('primary_rune_three', models.IntegerField()),
                ('primary_rune_four', models.IntegerField()),
                ('secondary_rune_one', models.IntegerField()),
                ('secondary_rune_two', models.IntegerField()),
                ('stat_rune_one', models.IntegerField()),
                ('stat_rune_two', models.IntegerField()),
                ('stat_rune_three', models.IntegerField()),
                ('creep_score', models.CharField(max_length=3)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.match')),
            ],
        ),
        migrations.CreateModel(
            name='RankedQueue',
            fields=[
                ('ranked_queue_id', models.IntegerField(primary_key=True, serialize=False)),
                ('solo_queue_tier', models.CharField(max_length=12)),
                ('solo_queue_rank', models.CharField(max_length=3)),
                ('solo_queue_league_points', models.CharField(max_length=3)),
                ('solo_queue_wins', models.CharField(max_length=4)),
                ('solo_queue_losses', models.CharField(max_length=4)),
                ('flex_queue_tier', models.CharField(max_length=12)),
                ('flex_queue_rank', models.CharField(max_length=3)),
                ('flex_queue_league_points', models.CharField(max_length=3)),
                ('flex_queue_wins', models.CharField(max_length=4)),
                ('flex_queue_losses', models.CharField(max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='matchhistory',
            name='summoner',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='id',
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='summoner_id',
        ),
        migrations.AddField(
            model_name='summoner',
            name='encrypted_id',
            field=models.CharField(default=0, max_length=63, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='summoner',
            name='profile_icon_id',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='summoner_level',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='summoner_name',
            field=models.CharField(max_length=16),
        ),
        migrations.DeleteModel(
            name='MatchHistory',
        ),
        migrations.AddField(
            model_name='rankedqueue',
            name='encrypted_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.summoner'),
        ),
        migrations.AddField(
            model_name='matchlist',
            name='encrypted_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.summoner'),
        ),
    ]
