# Generated by Django 3.1.7 on 2021-05-12 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_remove_participant_ban'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='creep_score',
        ),
    ]
