# Generated by Django 3.1.7 on 2021-05-12 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_remove_participant_creep_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='encrypted_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='search.summoner'),
            preserve_default=False,
        ),
    ]
