# Generated by Django 3.1.7 on 2021-05-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_participant_encrypted_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='encrypted_id',
            field=models.CharField(max_length=63),
        ),
    ]
